name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Deploy to VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USER: ${{ secrets.VM_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $VM_HOST >> ~/.ssh/known_hosts
        
        # Deploy new version
        ssh $VM_USER@$VM_HOST << EOF
          mkdir -p ~/app-new
          scp -r ./* $VM_USER@$VM_HOST:~/app-new
          pm2 start ~/app-new/server.js --name api-new || pm2 restart api-new
          
          # Wait for new instance to be ready
          sleep 5
          
          # Switch to new version
          pm2 stop api || true
          mv ~/app ~/app-old || true
          mv ~/app-new ~/app
          pm2 delete api-new
          pm2 start ~/app/server.js --name api
          
          # Clean up old version
          rm -rf ~/app-old
        EOF