name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install  # Use npm install instead of npm ci

    - name: Deploy to VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VM_HOST: ${{ secrets.VM_HOST }}
        VM_USER: ${{ secrets.VM_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key
        chmod 600 /tmp/private_key
        ssh -o StrictHostKeyChecking=no -i /tmp/private_key $VM_USER@$VM_HOST "sudo pkill -f 'node index.js' || true"
        scp -i /tmp/private_key -r . $VM_USER@$VM_HOST:/path/to/deploy
        ssh -i /tmp/private_key $VM_USER@$VM_HOST "cd /path/to/deploy && sudo nohup node index.js > output.log 2>&1 &"
